(define (problem solve)
    (:domain cleaner)
    (:objects 
        room1 room2 room3 room4 room5 socks_basket robot 
    )
    (:init
        (room room1)
        (room room2) 
        (room room3) 
        (room room4) 
        (room room5) 
        (robot robot)
        (basket socks_basket)
        
        (have_basket room2)
        (have_socks room1)
        (have_socks room2)
        (have_socks room3)
        (have_socks room4)
        (have_socks room5)
        (dirty room1)
        (dirty room2)
        (dirty room3)
        (dirty room4)
        (dirty room5)
        (have_robot room5)
        (fullPower robot)
        (have_charging room1)

    )
    (:goal                                               
        (and
            (clean room1)
            (clean room2)
            (clean room3)
            (clean room4)
            (clean room5)
            (fullPower robot)
            (not(have_socks room1))
            (not(have_socks room2))
            (not(have_socks room3))
            (not(have_socks room4))
            (not(have_socks room5))
            (not(full_of_socks robot))
        )
    )
)